BUILDING.md
README.md
docs/api/index.md
docs/articles/advanced_topics/buttons.md
docs/articles/audio/lavalink/configuration.md
docs/articles/audio/lavalink/music_commands.md
docs/articles/audio/voicenext/transmit.md
docs/articles/basics/first_bot.md
docs/articles/beyond_basics/intents.md
docs/articles/commands/command_attributes.md
docs/articles/commands/intro.md
docs/articles/interactivity.md
docs/articles/misc/nightly_builds.md
docs/articles/preamble.md
docs/faq.md

[T2](https://bugs.aitsys.dev/T2)

Rebrand DCS

---

appveyor.yml

Sticker Create is broken atm.
* Hardware:
* Toolchain:
* SDK:

Bump 9.6.1

---

appveyor.yml

* Hardware:
* Toolchain:
* SDK:

Release 9.6.2

---

DisCatSharp.ApplicationCommands/ApplicationCommandsExtension.cs
DisCatSharp.ApplicationCommands/ApplicationCommandsPermissionContext.cs
DisCatSharp/Entities/Application/DiscordApplicationCommandPermission.cs

Pre-PR.
@Auros please lemme know when ready

Implement ApplicationCommands Permissions

---

DisCatSharp.ApplicationCommands/DisCatSharp.ApplicationCommands.csproj
DisCatSharp.CommandsNext/DisCatSharp.CommandsNext.csproj
DisCatSharp.Common/DisCatSharp.Common.csproj
DisCatSharp.VoiceNext/DisCatSharp.VoiceNext.csproj
DisCatSharp/DisCatSharp.csproj
README.md
Version.targets
appveyor.yml

Release of new ApplicationCommandsPermissions
Big thanksy to @Auros :3 :heart:
Co-Authored-By: Auros Nexus <41306347+Auros@users.noreply.github.com>

[9.8.1] Implement Application Command Permissions

---

README.md
appveyor.yml

* Hardware:
* Toolchain:
* SDK:

Bump 9.8.3-nightly

---

DisCatSharp/Entities/Invite/DiscordInvite.cs
DisCatSharp/Entities/Invite/DiscordInviteGuild.cs

**DiscordInviteGuild:**
**DiscordInvite:**

Add missing fields to DiscordInvite Entity

---

appveyor.yml

* Hardware:
* Toolchain:
* SDK:

Bump 9.8.3

---

DisCatSharp.Hosting/DiscordHostedService.cs

... pay no attention to the xml fields 👀 
**cough**

removed unnecessary xml tags

---

DisCatSharp.Hosting.Tests/HostTests.cs

Tests have been addressed and are now passing with new method of doing things

Must initialize extensions so this works without connecting the client

---

DisCatSharp/Clients/DiscordClient.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs
DisCatSharp/Net/Rest/Endpoints.cs

Implement raw request

---

DisCatSharp/Entities/Guild/DiscordMember.cs
DisCatSharp/Net/Abstractions/Rest/RestGuildPayloads.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs

This PR adds the following methods to DiscordMember:
```cs
await DiscordMember.TimeOutAsync(DateTimeOffset, "Bad behavior);
await DiscordMember.TimeOutAsync(TimeSpan, "Bad behavior);
await DiscordMember.TimeOutAsync(DateTime, "Bad behavior");
await DiscordMember.RemoveTimeOutAsync("Behaves again");
```

Add Timeout function

---

DisCatSharp/Entities/Interaction/DiscordFollowupMessageBuilder.cs
DisCatSharp/Entities/Interaction/DiscordInteractionResponseBuilder.cs
DisCatSharp/Entities/Message/DiscordMessageBuilder.cs
DisCatSharp/Entities/Message/DiscordMessageFile.cs
DisCatSharp/Entities/Webhook/DiscordWebhookBuilder.cs
DisCatSharp/Net/Abstractions/Rest/RestWebhookPayloads.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs
DisCatSharp/Net/Rest/RestClient.cs

This PR adds support to set a description aka. alt text to files send in interaction builders, webhook builders and message builders.

Add support for file description (aka. Alt Text)

---

DisCatSharp/Entities/Guild/DiscordGuild.cs
DisCatSharp/Entities/Guild/DiscordMember.cs

* Hardware:
* Toolchain:
* SDK:

Add timeout shortcut to DiscordGuild

---

DisCatSharp/Clients/DiscordClient.Dispatch.cs

Fixed naming. Removed unused using statement

Fixed Naming

---

DisCatSharp/Entities/Interaction/DiscordInteractionResponseBuilder.cs

Since the ephemeral boolean is defaulted to false
AsEphemeral should default to true

AsEphemeral defaults as true

---

DisCatSharp.ApplicationCommands/ApplicationCommandsConfiguration.cs
DisCatSharp.ApplicationCommands/ApplicationCommandsExtension.cs

Auto-Defer slash and context menu commands if requested.

Implement AutoDefer

---

DisCatSharp.ApplicationCommands/ApplicationCommandsExtension.cs
DisCatSharp.ApplicationCommands/Workers/ApplicationCommandWorker.cs
DisCatSharp.CommandsNext/CommandsNextConfiguration.cs
DisCatSharp.CommandsNext/CommandsNextExtension.cs
DisCatSharp.CommandsNext/CommandsNextUtilities.cs
DisCatSharp.Common/Types/MemoryBuffer.cs
DisCatSharp.Common/Utilities/AsyncEvent/AsyncEvent.cs
DisCatSharp.Common/Utilities/Extensions.cs
DisCatSharp.Hosting/ConfigurationExtensions.cs
DisCatSharp.Interactivity/EventHandling/Components/ComponentEventWaiter.cs
DisCatSharp.Interactivity/EventHandling/Components/ModalEventWaiter.cs
DisCatSharp.Interactivity/EventHandling/Requests/PaginationRequest.cs
DisCatSharp.Interactivity/InteractivityExtension.cs
DisCatSharp/Clients/BaseDiscordClient.cs
DisCatSharp/Clients/DiscordClient.Dispatch.cs
DisCatSharp/Entities/Application/DiscordApplicationCommandLocalization.cs
DisCatSharp/Entities/Channel/DiscordChannel.cs
DisCatSharp/Entities/Guild/DiscordGuild.cs
DisCatSharp/Entities/Guild/DiscordRole.cs
DisCatSharp/Entities/Interaction/Components/Select/DiscordSelectComponent.cs
DisCatSharp/Entities/Message/DiscordMessage.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs
DisCatSharp/RingBuffer.cs

`foreach` and LINQ ftw!
Slightly breaking in a few minor places.
P.S.: Due to the removal of several superfluous `.ToArray` calls this should genuinely increase performance!

No more raw for-loops!

---

README.md

And test telegram notification
* Hardware:
* Toolchain:
* SDK:

Remove Discord Server reference from README

---

DisCatSharp.Docs/docfx.json

Export raw docs api to special folder
Closes {T209}

Raw API for docs

---

DisCatSharp/Clients/DiscordClient.Dispatch.cs
DisCatSharp/Entities/Channel/DiscordChannel.cs
DisCatSharp/Entities/Guild/DiscordAuditLogObjects.cs
DisCatSharp/Entities/Guild/DiscordGuild.AuditLog.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs

- Exposed AvailableTags object is now read-only
- Handle "available_tags" in channel update

Forum tag changes

---

DisCatSharp/Entities/Channel/DiscordChannel.cs

Honestly not worth a PR but I can't push to main ._.

Fix webhooks for threads

---

DisCatSharp/Clients/DiscordClient.cs
DisCatSharp/Entities/Channel/DiscordChannel.cs
DisCatSharp/Entities/Guild/DiscordGuild.cs
DisCatSharp/Entities/ThreadAndForum/DiscordThreadChannel.cs
DisCatSharp/Entities/Webhook/DiscordWebhook.cs

Add try variants to all getter methods

---

DisCatSharp.Docs/articles/misc/voice_activities.md
DisCatSharp.Docs/articles/misc/voiceactivities.md
DisCatSharp.Docs/articles/toc.yml

Added documentation for Voice Activities
Fixes {T} (aitsys.dev issue)
* Hardware:
* Toolchain:
* SDK:

Add Voice Activities Article

---

DisCatSharp/Entities/Guild/DiscordGuild.cs

Fixed ModifyCommunitySettingsAsync() to require the rules and public updates channel because if not provided the method will error.
Fixes {T} (aitsys.dev issue)
* Hardware:
* Toolchain:
* SDK:

Fixed ModifyCommunitySettingsAsync

---

DisCatSharp/Entities/Guild/DiscordGuild.Features.cs

Add missing guild features

---

DisCatSharp.ApplicationCommands/ApplicationCommandsExtension.cs
DisCatSharp.ApplicationCommands/Workers/ApplicationCommandWorker.cs

Tested by causing the changed exceptions.

Add command name of the problematic command to exception messages in app commands

---

DisCatSharp/Entities/Guild/ThreadAndForum/DiscordThreadChannel.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs

Reverts Aiko-IT-Systems/DisCatSharp#251

Revert "feat: Paginated thread members"

---

DisCatSharp/Entities/Guild/ThreadAndForum/DiscordThreadChannel.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs

Fixes {T} (aitsys.dev issue)
* Hardware:
* Toolchain:
* SDK:

feat: Paginated thread members

---

DisCatSharp/Clients/BaseDiscordClient.cs
DisCatSharp/Clients/DiscordClient.cs
DisCatSharp/Entities/Application/DiscordApplication.cs
DisCatSharp/Entities/Guild/DiscordGuild.cs
DisCatSharp/Entities/User/DiscordUser.cs
DisCatSharp/Entities/Webhook/DiscordWebhookBuilder.cs
DisCatSharp/Enums/Application/ApplicationDiscoverabilityState.cs
DisCatSharp/Enums/Application/ApplicationDiscoveryFlags.cs
DisCatSharp/Enums/Application/ApplicationVerificationState.cs
DisCatSharp/Enums/Application/RpcApplicationState.cs
DisCatSharp/Enums/Application/StoreApplicationState.cs
DisCatSharp/Net/Abstractions/Rest/RestApplicationPayloads.cs
DisCatSharp/Net/Abstractions/Rest/RestGuildPayloads.cs
DisCatSharp/Net/Abstractions/Rest/RestWebhookPayloads.cs
DisCatSharp/Net/Abstractions/Transport/TransportApplication.cs
DisCatSharp/Net/Models/GuildEditModel.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs
DisCatSharp/Net/Rest/Endpoints.cs

- Added /applications/@me `GET` & `PATCH`
- Implemented method `BaseDiscordClient.UpdateCurrentApplicationInfoAsync`
- Added guild home header property
- Added `DiscordClient.GetCurrentApplicationInfoAsync` (uses new route)
- Added properties to `DiscordApplication`:
- `ApproximateGuildCount`
- `InteractionsEndpointUrl`
- `RedirectUris`
- `Guild` (Partial)
- Added more flags & states
- Added `AsSilentMessage` & `SuppressEmbeds` to `DiscordFollowupMessageBuilder`, `DiscordInteractionResponseBuilder` & `DiscordWebhookBuilder`
- Added home header modify method

feat: Application rework

---

README.md

Fixes a minor grammar mistake.
N/A

fix(README): minor grammar mistake

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/documentation.yml
.github/workflows/documentation_test.yml
.github/workflows/release.yml
DisCatSharp.ApplicationCommands/DisCatSharp.ApplicationCommands.csproj
DisCatSharp.CommandsNext/DisCatSharp.CommandsNext.csproj
DisCatSharp.Common/DisCatSharp.Common.csproj
DisCatSharp.Configuration/DisCatSharp.Configuration.csproj
DisCatSharp.Experimental/DisCatSharp.Experimental.csproj
DisCatSharp.Hosting.DependencyInjection/DisCatSharp.Hosting.DependencyInjection.csproj
DisCatSharp.Hosting/DisCatSharp.Hosting.csproj
DisCatSharp.Interactivity/DisCatSharp.Interactivity.csproj
DisCatSharp.Lavalink/DisCatSharp.Lavalink.csproj
DisCatSharp.Targets/Library.targets
DisCatSharp.VoiceNext.Natives/DisCatSharp.VoiceNext.Natives.csproj
DisCatSharp.VoiceNext/DisCatSharp.VoiceNext.csproj
DisCatSharp/DisCatSharp.csproj

feat: re-enable net6

---

DisCatSharp.Targets/DisCatSharp.targets

* Hardware:
* Toolchain:
* SDK:

fix: RunAnalyzersDuringBuild to false

---

DisCatSharp.ApplicationCommands/ApplicationCommandsConfiguration.cs
DisCatSharp.ApplicationCommands/ApplicationCommandsExtension.cs
DisCatSharp.ApplicationCommands/EventArgs/Module/ApplicationCommandsModuleStartupFinishedEventArgs.cs
DisCatSharp/Net/Rest/RestClient.cs

fix: remove trace from debug lol

fix: application commands work now fully

---

DisCatSharp/Entities/Guild/DiscordBulkBanResponse.cs
DisCatSharp/Entities/Guild/DiscordGuild.cs
DisCatSharp/Net/Abstractions/Rest/RestGuildPayloads.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs
DisCatSharp/Net/Rest/Endpoints.cs

feat: bulk ban

---

DisCatSharp.CommandsNext/CommandsNextExtension.cs
DisCatSharp/Clients/DiscordClient.Dispatch.cs
DisCatSharp/Entities/Message/DiscordForwardedMessage.cs
DisCatSharp/Entities/Message/DiscordMessage.cs
DisCatSharp/Entities/Message/DiscordMessageReference.cs
DisCatSharp/Entities/Message/DiscordMessageSnapshots.cs
DisCatSharp/Entities/User/DiscordConnection.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs
DisCatSharp/Utilities.cs

Implementation of Discord's message forwarding feature.

feat: message forwarding

---

DisCatSharp/Clients/DiscordClient.EventHandlers.cs

This PR adds a Dictionary for automatically registered Event Handlers so they can be easily accessed.

Added Dictionary of automatically registerd Event Handlers

---

DisCatSharp/DisCatSharp.csproj

Fix build warnings; tackles #595

---

DisCatSharp.Interactivity/Helpers/InteractivityHelpers.cs
DisCatSharp.Tools/DisCatSharp.Analyzer/DisCatSharp.Analyzer/DisCatSharp.Analyzer.csproj
DisCatSharp/Clients/DiscordOAuth2Client.cs
DisCatSharp/Enums/Message/MessageFlags.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs

 [Part 3] Some improvements made during working on Hatsune Miku
