Aiko-IT-Systems/DisCatSharp

DisCatSharp.Hosting/DiscordHostedService.cs
DisCatSharp/Clients/BaseDiscordClient.cs
DisCatSharp/DiscordConfiguration.cs

Separated the extension initialization and client creation
Extension method is overridable, and invoked after connecting
Exposed Provider / Configuration to derived classes instead of having to pass it around all the time
Added a DI Constructor for DiscordConfiguration.
This is used by ActivatorUtilities to auto insert things via ServiceProvider, thus allowing DI to flow properly rather than manually setting the client's service provider
Updated Services to ServiceProvider for consistency

Adjusted DiscordHostedService Initialization Approach

---

README.md

This PR simply makes the discord server easier to find in the README by adding it to the text below the header `Where is the Changelog?`.

Make Discord server easier to find

---

DisCatSharp/Enums/Interaction/ButtonStyle.cs
DisCatSharp/Net/Serialization/DiscordComponentJsonConverter.cs

Currently Link buttons are fetched as buttons due to the json converter not checking the style.
This PR aims to fix this and allow link buttons to be fetched as DiscordLinkButtonComponents instead of DiscordButtonComponents.
* Hardware: Test bot running on Mac OS Monetary
* Toolchain:
* SDK: .Net 6

Add support for link buttons when fetching components

---

DisCatSharp.ApplicationCommands/Workers/ApplicationCommandWorker.cs

Slash commands that sit under two slash command groups where not having their options registered correctly.
Example command
```cs
[SlashCommandGroup("top_level_command", "top level group")]
public class MySlashCommandGroups : ApplicationCommandsModule
{
[SlashCommandGroup("mid_level", "mid level group")]
public class MidLevelGroup : ApplicationCommandsModule
{
[SlashCommand("test_command", "test commands")]
public async Task TestCommand(InteractionContext ctx,
[Option("repeat_this", "repeats the text")] string repeatMe)
{
await ctx.CreateResponseAsync(InteractionResponseType.ChannelMessageWithSource, new …
```

Fix sub options not being added to commands inside of two command groups

---

DisCatSharp/Entities/Embed/DiscordEmbedBuilder.cs
DisCatSharp/Entities/Embed/DiscordEmbedField.cs

Currently, given a `DiscordEmbedBuilder` `builder` you can modify the contents of its fields without regard for the fields' invariants using the following: `builder.Fields[0].Name = null`.
This PR alleviates this by moving all necessary invariants to the setters of the appropriate variables. Additionally the user is now allowed to utilize `DiscordEmbedField`s directly, as this can be useful, e.g. when wanting to create a collection of them via Linq mapping.
I've decided to keep the original `AddField` method around, while marking it with `Obsolete` as to both maintain backwards compatibility as well as indicate to users that they should utilize the manual construction of fields. This can of course be changed as requested.
Due to the triviality …

Embed Fields Upgrade

---

DisCatSharp/Entities/Channel/DiscordChannel.cs
DisCatSharp/Entities/Message/DiscordMessage.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs

Fixed threads not having a `Discord` object assigned on creation, leading to `NullReferenceException` upon using them.
I also fixed threads created from messages not including a thread type in their payload, although I'm unsure if this actually caused issues in practice.
Simply created a test bot and tested the associated calls (`DiscordChannel.CreateThreadAsync` and `DiscordMessage.CreateChannelAsync`) manually.
I'm not sure if there is some test driver that supports automatically testing this kind of thing? If there is, let me know!

Fix threads

---

DisCatSharp.ApplicationCommands/ApplicationCommandsExtension.cs

Previously those 2 `if (ex is BadRequestException brex)` weren't actually true as the Exception thrown are ArragateExcpetions. 
This should now properly inform the user what the problem actually is. The change from `JsonMessage` to `WebResponse.Response` is because the JsonMessage will always be "Invalid Form Body" and not actually show you what the error is. We could maybe format that a bit better in the future but for now, this should improve the current situation of having no information at all to go off of.

Proper exception log when registering app commands fails

---

DisCatSharp/Entities/Guild/DiscordGuild.AuditLog.cs
DisCatSharp/Enums/Guild/AuditLogActionType.cs

Fix 2 issues my bot has been reporting for a few days.
In addition, i added some missing documentation in [AuditLogActionType.cs](https://github.com/Aiko-IT-Systems/DisCatSharp/compare/fix-cast-auditlog?expand=1#diff-60396f7551ed6df25f3cde8ed49f44790558f25e17679fa0ee4e9c26eefa9bae). 
I also added placeholder handling for `AuditLogActionType.ApplicationCommandPermissionUpdate`, this needs to be handled in a future update but this goes beyond my expertise (~~and my willingness to familiarize myself with our audit log system without help lol~~).
As usually, i tested these changes with my bot.
```cs
System.AggregateException: One or more errors occurred. (Unable to cast object of type 'System.Int64' to type 'System.Int32'.)
---> System.InvalidCastException: Unable to cast object of type …
```

Fix ChannelFlagsChange Cast & NullReference

---

DisCatSharp/Clients/DiscordClient.Dispatch.cs
DisCatSharp/Clients/DiscordClient.cs
DisCatSharp/Entities/Channel/DiscordChannel.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs

Two issues:
- `DiscordClient.GetChannelAsync` caused `NullReferenceException` when there were no tags
- Tags were not being initialized consistently

Fix tags initialization

---

DisCatSharp/Clients/DiscordClient.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs

Adds `DiscordClient.GetGuildWidgetAsync(ulong)`, `.TryGetGuildWidgetAsync(ulong)`
Hacktober Task 8: https://discord.com/channels/858089281214087179/1025281336975556659

Fetch widget

---

DisCatSharp/Entities/Emoji/DiscordEmoji.cs

Fixes (DiscordEmoji Equals issue)
First of all, I'm not good at English.
i try to use SendPaginatedMessageAsync with PaginationEmojis.
when i react emoji, message was modified but message content wasn't changed.
because DiscordEmoji operator == is just compare emoji id and PaginationEmojis Id is all 0 so PaginateAsync is always return SkipLeft.
* OS: Windows11 22H2 22621.1413 …

fix: DiscordEmoji operator == add compare name

---

DisCatSharp.Docs/articles/modules/application_commands/events.md
DisCatSharp.Docs/articles/modules/application_commands/intro.md
DisCatSharp.Docs/articles/modules/application_commands/options.md
DisCatSharp.Docs/articles/modules/application_commands/translations/using.md

Changes `context` to `ctx` in the Application Commands articles' example code to match the rest of the documentation.

docs: uniform appCommands example code

---

DisCatSharp/Clients/DiscordClient.cs

Fixed all .TryGet methods I found. Prior to my change, they weren't using the normal out var pattern and were prone to still throwing errors which may be unexpected due to the "Try" in the name.
- [] I have made corresponding changes to the documentation
- [] Any dependent changes have been merged and published in downstream modules

Fixed .TryGet methods to follow the out var pattern

---

DisCatSharp.ApplicationCommands/ApplicationCommandsExtension.cs
DisCatSharp.ApplicationCommands/Entities/RegisteredDiscordApplicationCommand.cs
DisCatSharp/Entities/Application/DiscordApplicationCommand.cs
DisCatSharp/Entities/Application/DiscordApplicationCommandOption.cs

Adds the `RegisteredDiscordApplicationCommand` which inherits `DiscordApplicationCommand`.
This child type adds 4 new properties: `CommandMethod`, `CommandType`, `ContainingType` and `CustomAttributes` to allow developers to embed more information into their commands. For example, for a custom help command.

feat: additional properties for app command registered commands

---

DisCatSharp.Lavalink/LavalinkGuildPlayer.cs

Fixes playing tracks not from youtube by sending the full url as identifier to lavalink.
Soundcloud is currently also broken, assuming all platforms that aren't youtube are broken.
May not replace all instances of `Identifier` to `Uri.ToString()`, please confirm @Lulalaby.

fix: Identifier requires full uri for non-yt links

---

.editorconfig
DisCatSharp.VoiceNext.Natives/DisCatSharp.VoiceNext.Natives.csproj
DisCatSharp.VoiceNext/VoiceNextConnection.cs
DisCatSharp/Entities/User/DiscordUser.cs

This PR fixes issue, where if bot joins a channel that already has people, and those people speak, their voice stutters first time they talk and is ok next time.
It happens because discord sends player joined event only AFTER person stops speaking first time. This means we don't have entry in _transmittingSsrCs and current logic kept recreating it on every packet leading to wrong gap/invalid order packet logic.
This PR also fixes naming issues (which exists in current repo) be labeled as errors (problem in jetbrains rider for example) and fixes DiscordUser comparison for nullable references.
Also voice next native auto copies dlls to bin for easier local testing.

Fix minor voiceNext issue

---

DisCatSharp.Tests/SafetyTests/DisCatSharp.SafetyTests.csproj
DisCatSharp/Entities/DiscordSignedLink.cs
DisCatSharp/Entities/DiscordUri.cs
DisCatSharp/Entities/Embed/DiscordEmbedVideo.cs
DisCatSharp/Entities/Message/DiscordAttachment.cs

This adds the signed attachment stuff from the old rework branch to `main`.
Still needs to be tested.

Signed Attachments

---

DisCatSharp.Docs/articles/topics/components/select_menus.md

* Hardware:
* Toolchain:
* SDK:

select_menus - Fixed spelling of "Deferred"

---

DisCatSharp/Entities/Channel/DiscordChannel.cs
DisCatSharp/Entities/Guild/DiscordGuild.cs
DisCatSharp/Entities/Guild/ThreadAndForum/ForumPostTag.cs
DisCatSharp/Net/Abstractions/Rest/RestChannelPayloads.cs
DisCatSharp/Net/Models/ChannelEditModel.cs
DisCatSharp/Net/Models/ForumChannelEditModel.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs

Added missing "default_forum_layout" property for DiscordChannel
Fixes [#436](https://github.com/Aiko-IT-Systems/DisCatSharp/issues/436)

Added missing "default_forum_layout" property for DiscordChannel

---

DisCatSharp.Docs/articles/misc/hosting.md

Added docs for Termux hosting
Adding Termux Hosting To Documentation For Alternative Self-Hosting, this is from a thread in the Discord server with the same header.
This has been tested on a samsung SM-A6060 on the latest version of Termux from F-Droid.
* Firmware version: -
* Hardware: samsung SM-A6060
* Toolchain: apt-get
* SDK: DotNET 8.0

Adding Termux Hosting To Docs

---

DisCatSharp/Net/Rest/RestClient.cs

So, I recently remember about #127 and sat up in my arm chair, my cigar was nearly ashed on my ashtray, I thought to myself "Surely they've done better, the library should be safe!". I pulled up my 1992 version of vim and git 1.2, cloned the repository, and started browsing. I sit there, clouded by the smoke as I browse [BaseDiscordClient](https://github.com/Aiko-IT-Systems/DisCatSharp/blob/603893017cf99ba1c889e9a1fa8f98a6be0b6263/DisCatSharp/Clients/BaseDiscordClient.cs), one property caught my attention: `Sentry`, I immediately thought of sentry exceptions and how greedy and easy it is to misconfigured sensitive information, my glasses dimmed as I browsed usages of this property... All of the sudden a certain class snuck up on me: The …

[SEVERE] Fix pepegga token logger round 2 uwu

---

DisCatSharp/Clients/BaseDiscordClient.cs
DisCatSharp/DiscordConfiguration.cs
DisCatSharp/Net/Rest/RestClient.cs
DisCatSharp/Utilities.cs

This PR further addresses #493 and #494.
~~@quinchs Feel free to double-check my work. I've used your method from #494 for this implementation, that's why i'm mentioning you.~~
I replaced the method, noticed the original wouldnt actually work properly.

Client-Side Sentry Filtering

---

DisCatSharp/Clients/BaseDiscordClient.cs
DisCatSharp/Clients/DiscordClient.cs
DisCatSharp/DiscordConfiguration.cs
DisCatSharp/Entities/Application/DiscordApplicationEmoji.cs
DisCatSharp/Entities/Emoji/DiscordEmoji.cs
DisCatSharp/Net/Abstractions/Rest/RestApplicationPayloads.cs
DisCatSharp/Net/Rest/DiscordApiClient.cs
RELEASENOTES.md

This implements [Application Emojis](https://discord.com/developers/docs/change-log#application-emoji) (THANKS MAISY).
Breaking change in `DiscordEmoji.TryFromName` (additional required parameter)
- `BaseDiscordClient.Emojis`-  (`IReadOnlyDictionary<ulong, DiscordApplicationEmoji>`)
- `DiscordClient.Emojis`-  (`IReadOnlyDictionary<ulong, DiscordApplicationEmoji>`)
- `DiscordClient.GetApplicationEmojisAsync(bool fetch = false)` - (`Task<IReadOnlyList<DiscordApplicationEmoji>>`)
- `DiscordClient.GetApplicationEmojiAsync(ulong id, bool fetch = false)` - (`Task<DiscordApplicationEmoji?>`)
- `DiscordClient.CreateApplicationEmojiAsync(string name, Stream image)` - (`Task<DiscordApplicationEmoji>`)
- `DiscordClient.ModifyApplicationEmojiAsync(ulong id, string name)` - …

feat: Application Emojis

---

DisCatSharp/Clients/DiscordClient.cs

fix: Thread-Safe Internal Dictionaries

---

DisCatSharp.Docs/articles/modules/audio/lavalink_v4/commands.md

because it is List<LavalinkTrack> -> so just .Frist()
* Hardware:
* Toolchain:
* SDK:

Fix error syntax document

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/documentation.yml
.github/workflows/documentation_test.yml
.github/workflows/internal-release.yml
.github/workflows/public-dev-release.yml
.github/workflows/release.yml
DisCatSharp.ApplicationCommands/DisCatSharp.ApplicationCommands.csproj
DisCatSharp.CommandsNext/DisCatSharp.CommandsNext.csproj
DisCatSharp.Common/DisCatSharp.Common.csproj
DisCatSharp.Configuration/DisCatSharp.Configuration.csproj
DisCatSharp.Experimental/DisCatSharp.Experimental.csproj
DisCatSharp.Hosting.DependencyInjection/DisCatSharp.Hosting.DependencyInjection.csproj
DisCatSharp.Hosting/DisCatSharp.Hosting.csproj
DisCatSharp.Interactivity/DisCatSharp.Interactivity.csproj
DisCatSharp.Lavalink/DisCatSharp.Lavalink.csproj
DisCatSharp.Targets/Library.targets
DisCatSharp.Targets/TestProject.targets
DisCatSharp.VoiceNext.Natives/DisCatSharp.VoiceNext.Natives.csproj
DisCatSharp.VoiceNext/DisCatSharp.VoiceNext.csproj

This pull request removes .NET 7 as it's not EOL as per https://versionsof.net/core/

chore!: removed .NET 7 support

---

DisCatSharp.ApplicationCommands/Context/BaseContext.cs
DisCatSharp.ApplicationCommands/DisCatSharp.ApplicationCommands.csproj
DisCatSharp.CommandsNext/DisCatSharp.CommandsNext.csproj
DisCatSharp.Common/DisCatSharp.Common.csproj
DisCatSharp.Configuration/DisCatSharp.Configuration.csproj
DisCatSharp.Docs/articles/modules/audio/lavalink_v4/advanced.md
DisCatSharp.Docs/articles/modules/audio/lavalink_v4/configuration.md
DisCatSharp.Docs/articles/modules/audio/lavalink_v4/docker.md
DisCatSharp.Docs/articles/modules/audio/lavalink_v4/queue.md
DisCatSharp.Docs/articles/modules/audio/lavalink_v4/setup.md
DisCatSharp.Docs/articles/toc.yml
DisCatSharp.Experimental/DisCatSharp.Experimental.csproj
DisCatSharp.Hosting.DependencyInjection/DisCatSharp.Hosting.DependencyInjection.csproj
DisCatSharp.Hosting/DisCatSharp.Hosting.csproj
DisCatSharp.Interactivity/DisCatSharp.Interactivity.csproj
DisCatSharp.Lavalink/DisCatSharp.Lavalink.csproj
DisCatSharp.Lavalink/Entities/DefaultQueueEntry.cs
DisCatSharp.Lavalink/Entities/IQueueEntry.cs
DisCatSharp.Lavalink/Entities/LavalinkTrack.cs
DisCatSharp.Lavalink/LavalinkConfiguration.cs
DisCatSharp.Lavalink/LavalinkGuildPlayer.cs
DisCatSharp.Lavalink/LavalinkQueue.cs
DisCatSharp.Lavalink/LavalinkRestClient.cs
DisCatSharp.Lavalink/Models/LavalinkPlayerUpdateModel.cs
DisCatSharp.Lavalink/Payloads/LavalinkRestPlayerUpdatePayload.cs
DisCatSharp.Targets/InternalsVisibleTo.targets
DisCatSharp.Tools/DisCatSharp.Analyzer/DisCatSharp.Analyzer/DisCatSharp.Analyzer.csproj
DisCatSharp.VoiceNext.Natives/DisCatSharp.VoiceNext.Natives.csproj
DisCatSharp.VoiceNext/DisCatSharp.VoiceNext.csproj
DisCatSharp/DisCatSharp.csproj

- Introduced a new `EditResponseAsync` method for string content.
- Created `DefaultQueueEntry` class for track playback handling.
- Updated `LavalinkConfiguration` with a customizable `QueueEntryFactory`.
- Refactored `LavalinkGuildPlayer` to utilize a static `QueueInternal` for guild-specific queues.
- Deprecated the `QueueEntries` property in favor of the new `Queue` property.
- Implemented a new thread-safe `LavalinkQueue<T>` class for queue operations.
I really like the short, not too long way of writing.
The `EditResponseAsync `method is used a lot and I think the input is mainly a content, so I added a method input which is string content, hope you agree.
tested the queue part with 3 servers and they work fine (only manual test, no …

Enhance queue management and interaction response
